### PR TITLE
Modded greenhouse

### LINKED ISSUE #35: Better Junimos Cant go into greenhouse [log]
image
https://smapi.io/log/060c2d2dbc8c4f09b649c9e9f5136b3e
The error is under the [game] selection option in the smapi log. the junimos will stand outside the greenhouse unable to go inside. the log will spam, the game will lag, and the junimos will be unable to do anything until the option is disabled. I haave progressive mode enabled and the junimos have been given the items to work. See images provided.
image
image
image
image
image
image

### PR DESCRIPTION
**Pull request by Miguel-Thewolf**
This pull contains #59 #60 #61 

It is work with multiple custom greenhouse buldings, even if they are in ginger island or any other location.

gnger island

tynigreenhouse

bj on tiny greenhouse

resolves #35

### CODE REVIEW

**Comment by hawkfalcon** [comment]
I broke this by merging your other PRs 😬

**Comment by Miguel-Thewolf** [comment]
> I broke this by merging your other PRs 😬

Thats is my current mod, mmmm i checkit

**Comment by Miguel-Thewolf** [comment]
<<<<<<< modded_greenhouse
            var hut = Util.GetHutFromId(__instance.HomeId);
            if (hut is null) return false;
            var id = __instance.HomeId;
=======
            if (__instance.home is null) {
                //BetterJunimos.SMonitor.Log($"No hut assigned");
                return false;
            }
            var id = ___netHome.Value;
>>>>>>> master

With fix to home propertie, any code is working but i have 

            var hut = Util.GetHutFromId(__instance.HomeId);
            if (hut is null) return false;
            var id = __instance.HomeId;

**Comment by hawkfalcon** [comment]
Sorry for long delay

**Comment by hawkfalcon** [comment]
Updated https://www.nexusmods.com/stardewvalley/mods/2221?tab=files

**Pull request merged**
